spring:
  config:
    activate:
      on-profile: "qa"



build:
  version: "2.0"
loans:
  message: "Welcome to EazyBank loans related QA APIs"
  contactDetails:
    name: "Jasica Ray -Product Owner"
    email: "jasica@eazybank.com"
  onCallSupport:
    -(666)666-1234
    -(666)623-1234

