server:
  port: 9092


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/eazybank?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: admin123
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      pool-name: HikariCP
      max-lifetime: 1800000
      connection-timeout: 20000

  jpa:
    hibernate:
      ddl-auto: update   # validate schema, avoids accidental table drops in prod
    show-sql: true        # disable in prod (can enable in dev)
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  config:
    import:
      - application-qa.yml
      - application-prod.yml

  jackson:
    serialization:
      write-dates-as-timestamps: false

  profiles:
    active: "qa"

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    com.eazybank: DEBUG   # your package logs
  file:
    name: logs/eazybank-app.log

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,threaddump,heapdump
  endpoint:
    health:
      show-details: always
  health:
    db:
      enabled: true

springdoc:   # if you use OpenAPI/Swagger
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true


build:
  version: "1.0"
loans:
  message: "Welcome to EazyBank loan related APIs"
  contactDetails:
    name: "John Doe - Developer"
    email: "john@eazybank.com"
  onCallSupport:
    -(555)555-1234
    -(555)523-1234
